apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-nodejs-dep2
  namespace: dmesure-msgpollingservice
spec:
  selector:
    matchLabels:
      app: helloworld-nodejs-dep2
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld-nodejs-dep2
    spec:
      containers:
        - name: helloworld-nodejs-dep2
          image: image-registry.openshift-image-registry.svc:5000/dmesure-msgpollingservice/helloworld-imagestream2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080